export const EVENTS = {
  SIGN_IN: 'SIGN_IN',
  O_AUTH: 'O_AUTH',
  O_AUTH_FACEBOOK: 'O_AUTH_FACEBOOK',
  O_AUTH_GOOGLE: 'O_AUTH_GOOGLE',

  SIGN_UP: 'REGISTRATION_EMAIL',
  CREATE_MANGA_STORY: 'CREATE_MANGA_STORY',
  CREATE_MANGA_STORY_GENRES_NEXT: 'CREATE_MANGA_STORY_GENRES_NEXT',
  CREATE_MANGA_STORY_LANGUAGES_NEXT: 'CREATE_MANGA_STORY_LANGUAGES_NEXT',
  CREATE_MANGA_STORY_LOOKING_FOR_NEXT: 'CREATE_MANGA_STORY_LOOKING_FOR_NEXT',
  CREATE_MANGA_STORY_MODEL_NEXT: 'CREATE_MANGA_STORY_MODEL_NEXT',
  CREATE_MANGA_STORY_DESCRIPTION_NEXT: 'CREATE_MANGA_STORY_DESCRIPTION_NEXT',
  CREATE_MANGA_STORY_TITLE_NEXT: 'CREATE_MANGA_STORY_TITLE_NEXT',
  CREATE_MANGA_STORY_STORY_NEXT: 'CREATE_MANGA_STORY_STORY_NEXT',
  PILOT_COMPLETED: 'PILOT_COMPLETED',
  CHARACTERS_COMPLETED: 'CHARACTERS_COMPLETED',
  PAGES_COMPLETED: 'PAGES_COMPLETED',
  TEMPLATES_COMPLETED: 'TEMPLATES_COMPLETED',
  PROJECT_UPLOADED: 'PROJECT_UPLOADED',
  PROJECT_PUBLISHED: 'PROJECT_PUBLISHED',

  // Profile
  UPDATE_FULL_NAME: 'UPDATE_FULL_NAME',
  ADDED_BIO: 'ADDED_BIO',
  ADDED_PHOTO: 'ADDED_PHOTO',
  ADDED_GENRES: 'ADDED_GENRES',
  SOCIAL_ACCOUNT: 'SOCIAL_ACCOUNT',
  ADDED_PORTFOLIO: 'ADDED_PORTFOLIO',
  ADDED_PORTFOLIO_PDF: 'ADDED_PORTFOLIO_PDF',
  ADDED_PORTFOLIO_TEXT: 'ADDED_PORTFOLIO_TEXT',
  COMMISION_CREATED: 'COMMISION_CREATED',
  COMMISION_DELETE: 'COMMISION_DELETE',
  COMMISION_EDIT: 'COMMISION_EDIT',
  COMMISION_SAVE: 'COMMISION_SAVE',
  ADDED_USER_TYPES: 'ADDED_USER_TYPES',
  CREATE_PROJECT_COMPLETE: 'CREATE_PROJECT_COMPLETE',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  UPDATE_USER_IN_MODAL: 'UPDATE_USER_IN_MODAL',
  CLOSE_UPDATE_USER_MODAL: 'CLOSE_UPDATE_USER_MODAL',

  // Project
  EDIT_PROJECT: 'EDIT_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  CREATE_PROJECT_START: 'CREATE_PROJECT_START',
  SHARED_PROJECT: 'SHARED_PROJECT',
  GO_TO_PRIVATE: 'GO_TO_PRIVATE',
  GO_TO_PUBLIC: 'GO_TO_PUBLIC',

  // Board
  CHANGE_BOARD_TITLE: 'CHANGE_BOARD_TITLE',
  CHANGE_BOARD_DESCRIPTION: 'CHANGE_BOARD_DESCRIPTION',
  CREATE_BOARD_CHARACTER: 'CREATE_BOARD_CHARACTER',
  CREATE_BOARD_TOOL: 'CREATE_BOARD_TOOL',
  CREATE_BOARD_BACKGROUND: 'CREATE_BOARD_BACKGROUND',
  ADDED_BOARD_PAGE: 'ADDED_BOARD_PAGE',

  // Task
  CHOOSED_TASK_ROLL_TYPE: 'CHOOSED_TASK_ROLL_TYPE',
  CHOOSED_TASK_COMMISSION_TYPE: 'CHOOSED_TASK_COMMISSION_TYPE',
  ADDED_TASK_DESCRIPTION: 'ADDED_TASK_DESCRIPTION',
  ADDED_TASK_PRICE: 'ADDED_TASK_PRICE',
  MINI_JOB_CREATED: 'MINI_JOB_CREATED',
  MINI_JOB_EDITED: 'MINI_JOB_EDITED',
  MINI_JOB_REMOVED: 'MINI_JOB_REMOVED',

  // Feed
  OPENED_POST: 'OPENED_POST',
  OPENED_ALL_COLLABORATION: 'OPENED_ALL_COLLABORATION',
  OPENED_ALL_PROFILES: 'OPENED_ALL_PROFILES',
  DAILY_WARM: 'DAILY_WARM',

  // Another user profile
  SHARED_MY_ACCOUNT: 'SHARED_MY_ACCOUNT',
  SHARED_ANOTHER_ACCOUNT: 'SHARED_ANOTHER_ACCOUNT',
  FOLLOW_ACCOUNT: 'FOLLOW_ACCOUNT',
  MESSAGED_ACCOUNT: 'MESSAGED_ACCOUNT',
  LIKE_PORTFOLIO: 'LIKE_PORTFOLIO',
  CHECKED_ACCOUNT_TABS: 'CHECKED_ACCOUNT_TABS',

  POST_COMMENT: 'POST_COMMENT',
  POST_LIKE: 'POST_LIKE',
  ADD_FEEDBACK: 'ADD_FEEDBACK',

  INVITE_SOMEONE: 'INVITE_SOMEONE',
  REQUEST_TO_JOIN: 'REQUEST_TO_JOIN',

  INVITE_ACCEPTED: 'INVITE_ACCEPTED',
  INVITE_REJECTED: 'INVITE_REJECTED',

  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',

  ADDED_COMMENT: 'ADDED_COMMENT',

  PUBLISH_MANGA_CAT: 'PUBLISH_MANGA_CAT',
  INVITE_MEMBER: 'INVITE_MEMBER',
  INVITE_MEMBER_LINK: 'INVITE_MEMBER_LINK',

  GET_MANGAFYD: 'GET_MANGAFYD',
};
