export const EVENTS = {
  SIGN_IN: 'SIGN_IN',
  O_AUTH: 'O_AUTH',
  SIGN_UP: 'SIGN_UP',
  CREATE_MANGA_STORY: 'CREATE_MANGA_STORY',
  CREATE_MANGA_STORY_GENRES_NEXT: 'CREATE_MANGA_STORY_GENRES_NEXT',
  CREATE_MANGA_STORY_LANGUAGES_NEXT: 'CREATE_MANGA_STORY_LANGUAGES_NEXT',
  CREATE_MANGA_STORY_LOOKING_FOR_NEXT: 'CREATE_MANGA_STORY_LOOKING_FOR_NEXT',
  CREATE_MANGA_STORY_MODEL_NEXT: 'CREATE_MANGA_STORY_MODEL_NEXT',
  CREATE_MANGA_STORY_DESCRIPTION_NEXT: 'CREATE_MANGA_STORY_DESCRIPTION_NEXT',
  CREATE_MANGA_STORY_TITLE_NEXT: 'CREATE_MANGA_STORY_TITLE_NEXT',
  CREATE_MANGA_STORY_STORY_NEXT: 'CREATE_MANGA_STORY_STORY_NEXT',
};
