export const EVENTS = {
  SIGN_IN: 'SIGN_IN',
  O_AUTH: 'O_AUTH',
  O_AUTH_FACEBOOK: 'O_AUTH_FACEBOOK',
  O_AUTH_GOOGLE: 'O_AUTH_GOOGLE',

  SIGN_UP: 'REGISTRATION_EMAIL',
  CREATE_MANGA_STORY: 'CREATE_MANGA_STORY',
  CREATE_MANGA_STORY_GENRES_NEXT: 'CREATE_MANGA_STORY_GENRES_NEXT',
  CREATE_MANGA_STORY_LANGUAGES_NEXT: 'CREATE_MANGA_STORY_LANGUAGES_NEXT',
  CREATE_MANGA_STORY_LOOKING_FOR_NEXT: 'CREATE_MANGA_STORY_LOOKING_FOR_NEXT',
  CREATE_MANGA_STORY_MODEL_NEXT: 'CREATE_MANGA_STORY_MODEL_NEXT',
  CREATE_MANGA_STORY_DESCRIPTION_NEXT: 'CREATE_MANGA_STORY_DESCRIPTION_NEXT',
  CREATE_MANGA_STORY_TITLE_NEXT: 'CREATE_MANGA_STORY_TITLE_NEXT',
  CREATE_MANGA_STORY_STORY_NEXT: 'CREATE_MANGA_STORY_STORY_NEXT',
  PILOT_COMPLETED: 'PILOT_COMPLETED',
  CHARACTERS_COMPLETED: 'CHARACTERS_COMPLETED',
  PAGES_COMPLETED: 'PAGES_COMPLETED',
  TEMPLATES_COMPLETED: 'TEMPLATES_COMPLETED',
  PROJECT_UPLOADED: 'PROJECT_UPLOADED',
  PROJECT_PUBLISHED: 'PROJECT_PUBLISHED',

  ADDED_BIO: 'ADDED_BIO',
  ADDED_GENRES: 'ADDED_GENRES',
  ADDED_PORTFOLIO: 'ADDED_PORTFOLIO',
  SOCIAL_ACCOUNT: 'SOCIAL_ACCOUNT',
  CREATE_PROJECT_START: 'CREATE_PROJECT_START',
  COMMISION_CREATED: 'COMMISION_CREATED',

  MINI_JOB_CREATED: 'MINI_JOB_CREATED',
  MINI_JOB_EDITED: 'MINI_JOB_EDITED',
  MINI_JOB_REMOVED: 'MINI_JOB_REMOVED',

  CREATE_PROJECT_COMPLETE: 'CREATE_PROJECT_COMPLETE',

  GO_TO_PRIVATE: 'GO_TO_PRIVATE',
  GO_TO_PUBLIC: 'GO_TO_PUBLIC',

  INVITE_SOMEONE: 'INVITE_SOMEONE',
  REQUEST_TO_JOIN: 'REQUEST_TO_JOIN',

  INVITE_ACCEPTED: 'INVITE_ACCEPTED',
  INVITE_REJECTED: 'INVITE_REJECTED',

  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_REJECTED: 'REQUEST_REJECTED',

  ADDED_COMMENT: 'ADDED_COMMENT',
};
