apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: front-app-dev
  name: front-app-dev
  namespace: mangafy-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: front-app-dev
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: front-app-dev
    spec:
      containers:
        - name: front-app-dev
          image: asia.gcr.io/mangafy/front:latest-dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Gi"
              cpu: "2.0"
          env:
            - name: ENV
              value: "development"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30